prow/cluster/02-plugin-config.yaml
prow/config/config.yaml
prow/config/plugins.yaml

Enabled config-updater plugin, it directly applies prow config on the ConfigMap so they were put in different folder than yamls for cluster creation and initial configuration

enabled config-updater plugin, raw configs in separate folder

---

prow/config/config.yaml

Job runs every time .prow.yaml (or .prow) is changed in test-infra repo. This job can be re-used for other repos.

Added inrepoconfig validator job to main config

---

prow/config/plugins.yaml

By default prow adds approved label to PRs created by repo owners, per https://github.com/nephio-project/nephio/issues/130 disabling it

disable auto approve

---

prow/config/plugins.yaml

This allows repo admins to force green status on the failing test as an exemption

Enable override plugin

---

images/gotests/Dockerfile

Moved gotests to debian based image added controller-gen, helpgen and type-scaffold

Adding controller-gen, helpgen and type-scaffold

---

prow/config/config.yaml

Images built from every commit will have prow BUILD_ID as a version and those build from release tags v.X.Y.Z will have that tag name as version

Image building and pushing for free5gc-operator

---

prow/config/config.yaml

GCSWEB app allows to browse prow's bucket to download build artifacts

Adding gcsweb browser

---

e2e/provision/playbooks/cluster.yml
e2e/provision/playbooks/roles/install/README.md
e2e/provision/playbooks/roles/install/molecule/default/converge.yml
e2e/provision/playbooks/roles/install/molecule/default/molecule.yml
e2e/provision/playbooks/roles/install/molecule/default/prepare.yml
e2e/provision/playbooks/roles/install/molecule/default/tests/test_default.py
e2e/provision/playbooks/roles/install/tasks/main.yml
e2e/provision/tox.ini

This Ansible role provides the tasks required for deploying Nephio services on target nodes, it consumes the tasks defined on the [kpt role](https://github.com/nephio-project/test-infra/tree/main/e2e/provision/playbooks/roles/kpt).
Related items:
* [Nephio installer](https://github.com/nephio-project/test-infra/tree/main/e2e/provision/playbooks/roles/kpt)
* [Nephio installation commands](https://github.com/nephio-project/nephio/issues/47#issuecomment-1524730928)

Create install ansible role

---

prow/config/config.yaml

got subdomain for gcsweb sorted do changing to FQDN

switching from IP to FQDN

---

e2e/provision/playbooks/roles/kpt/README.md
e2e/provision/playbooks/roles/kpt/molecule/default/converge.yml
e2e/provision/playbooks/roles/kpt/molecule/default/molecule.yml
e2e/provision/playbooks/roles/kpt/molecule/default/prepare.yml
e2e/provision/playbooks/roles/kpt/molecule/default/tests/test_default.py
e2e/provision/playbooks/roles/kpt/tasks/main.yml
e2e/provision/tox.ini

The `kpt` Ansible role is used as helper for some tasks defined in the `bootstrap` and `install` Ansible roles. The initial version didn't have unit tests and documentation. This change provides some information and integration tests.

Add molecule tests to kpt Ansible role

---

e2e/provision/.ansible-lint
e2e/provision/playbooks/library/kpt.py
e2e/provision/playbooks/roles/bootstrap/molecule/default/converge.yml
e2e/provision/playbooks/roles/bootstrap/molecule/default/molecule.yml
e2e/provision/playbooks/roles/install/molecule/default/molecule.yml
e2e/provision/playbooks/roles/kpt/molecule/default/molecule.yml
e2e/provision/playbooks/roles/kpt/tasks/main.yml

Wrapping the kpt client commands in to an ansible module can provide a better control on the output and avoid false positives during the execution. This change introduces the kpt ansible module.

Add kpt ansible module

---

prow/config/config.yaml

Fixes https://github.com/nephio-project/sig-release/issues/34

nephio-operator image build

---

e2e/provision/Vagrantfile
e2e/provision/playbooks/roles/bootstrap/defaults/main.yml
e2e/provision/playbooks/roles/bootstrap/tasks/system-setup.yml
e2e/terraform/main.tf

This change implements this [change](https://github.com/nephio-project/sig-release/issues/37) and fixes the Vagrantfile and gitea default user defined in the Bootstrap Ansible role

Use sysctl Ansible module

---

e2e/tests/004-free5gc-operator.yaml

Enable the Free5GC operator to be deployed on all workload clusters
- Remove 'edge' in name
- Remove matching labels in 'objectSelector'

Enable the Free5GC operator to be deployed on all workload clusters

---

e2e/provision/gce_install_sandbox.sh
e2e/terraform/main.tf
e2e/terraform/output.tf
e2e/terraform/variables.tf

Both process uses the same amount of cloud resources with the major distinction to consume different sources. This change provides a new set of Terraform variables to control the number of `e2e` and `lab` instances. Ideally, they shouldn't have the same value, but maybe there are cases when both instances are needed
> Note, the format of the scripts were fixed with `terraform fmt`

Proposal to reuse e2e and lab terraform scripts

---

e2e/provision/Vagrantfile

Tests done on:
Laptop 1: Windows 11 i7-10750H (16 T) 32GB ram (8VCPU 32GB)
Laptop 2: Windows 10 i5-7200U (4T) 24GB ram (4VCPU 16RAM)
Steps:
- install git
- install virtualbox
- install vagrant
- open git bash
- `git config --global core.autocrlf false`
- `git clone https://github.com/nephio-project/test-infra.git && cd test-infra/e2e/provision`
- `vagrant up`
[Disabling host ssh key check for connecting into the vm](https://docs.ansible.com/ansible/latest/inventory_guide/connection_details.html#managing-host-key-checking), in order to run the installation script without having the machine key.
In the ansible.cfg there is already this parameter (host_key_checking = False) but on windows it would fail:
`fatal: [hostname] => SSH Error: Host key verification failed.
while connecting to …

Vagrant Sandbox provisioning support for Windows

---

e2e/provision/README.md

- Add title2 for steps
- Add command to create secrets for edge clusters
- Align style guide with https://kubernetes.io/docs/contribute/style/style-guide/
- Use simple and direct language
- Address the reader as "you"
- Code snippet formatting: Don't include the command prompt
- Code snippet formatting: Separate commands from output

Improve editorial description

---

e2e/provision/gce_init.sh

Adding user in Docker group also requires some activation via restarting the VM or launching newgrp command (cf https://docs.docker.com/engine/install/linux-postinstall/)

Activate changes in Docker group

---

e2e/tests/004-free5gc-operator.yaml
e2e/tests/004.sh

Update to use the recent operator, and test for that in the deployment.

Use v3 of the free5gc operator package

---

e2e/lib/k8s.sh
e2e/tests/007-edge-free5gc-ueransim.yaml
e2e/tests/007.sh

Simple test:
1) deploy ueransim in ueransim ns
2) wait till it's in a ready state, e.g. pods are running
3) find a pod in ns ueransim with labels `-l app=ueransim -l component=ue`.
4) exec `ping -I uesimtun0 google.com` in a pod found in 3). That fails if uesimtun0 doesn't exist, e.g. session setup failed, or if there is no reachability, e.g. so problem with UPF.

Add 007 ueransim test.

---

e2e/provision/README.md
e2e/provision/gce_init.sh
e2e/provision/gce_install_sandbox.sh
e2e/provision/hacks/resolve_secrets.sh

This PR:
- Allows the initialization variables to be overridden on invocation without using the get metadata, for example by using
cat gce_init.sh | sudo NEPHIO_DEBUG=true NEPHIO_RUN_E2E=false bash
- Creates the docker use before management cluster invocation to allow the kpt fn apply commands in the
gce_install_sandbox.sh script to run on the nephio user.

Updated init script to allow metadata override

---

e2e/provision/README.md

- add link to Gitea UI
- correct command for `kpt alpha rpkg clone`
- correct output for `kpt alpha rpkg get --name nephio-workload-cluster`: v7 is false
- correct output for `kubectl get machinesets`: number of nodes should be 1
- add output for `kubectl apply -f test-infra/e2e/tests/004-free5gc-operator.yaml`

 Minor corrections

---

prow/config/plugins.yaml

This allows to re-check cla status separate from GitHub's own mechanisms

add CLA plugin

---

e2e/provision/install_sandbox.sh

Python virtual environments are helpful to isolate package dependencies, but in this case it's causing some [random failures in the CI](http://prow.nephio.io/view/gs/prow-nephio-sig-release/pr-logs/pull/nephio-project_test-infra/98/e2e/1669358866636214272#1:build-log.txt%3A392). This change removes that OS dependency.

Drop python3-virtualenv dependency 

---

.gitignore
e2e/provision/README.md
e2e/provision/playbooks/cluster.yml
e2e/tests/002-topo.gotmpl
e2e/tests/002.sh

This change provides an intermediate step to interconnect worker nodes.
Solves: https://github.com/nephio-project/nephio/issues/270
\cc @johnbelamaric @henderiw

Add test step interconnect clusters

---

e2e/provision/install_sandbox.sh
e2e/provision/playbooks/roles/bootstrap/defaults/main.yml
e2e/provision/playbooks/roles/bootstrap/molecule/default/tests/test_default.py
e2e/provision/playbooks/roles/bootstrap/tasks/load-gtp5g-module.yml
e2e/provision/playbooks/roles/bootstrap/tasks/main.yml
e2e/provision/playbooks/roles/bootstrap/vars/ubuntu-20.yml
e2e/provision/playbooks/roles/bootstrap/vars/ubuntu-22.yml

There are some [random failures](http://prow.nephio.io/view/gs/prow-nephio-sig-release/pr-logs/pull/nephio-project_test-infra/93/e2e/1669099496241369088#1:build-log.txt%3A6717) on the CI to detect the right package for gcc. This change tries to cover all the possibilities.

Import the bash gtp5g installation into Ansible role

---

e2e/provision/install_sandbox.sh
e2e/provision/playbooks/cluster.yml
e2e/provision/playbooks/library/kpt.py
e2e/provision/playbooks/roles/bootstrap/tasks/main.yml
e2e/provision/playbooks/roles/install/tasks/main.yml
e2e/provision/playbooks/roles/kpt/molecule/default/molecule.yml
e2e/provision/playbooks/roles/kpt/tasks/main.yml
e2e/provision/playbooks/roles/kpt/tasks/wait_deployments.yml

The CI requires to constantly display progress to [avoid timeout issues](http://prow.nephio.io/view/gs/prow-nephio-sig-release/pr-logs/pull/nephio-project_test-infra/105/e2e/1669488808086736896#1:build-log.txt%3A47364). This change fixes the kpt module implementation and imports some bash instructions.

Import kpt bash instructions in Ansible

---

e2e/provision/playbooks/roles/bootstrap/tasks/main.yml

This change ensures all handlers operations occur before the management cluster creation.
Solves: https://github.com/nephio-project/nephio/issues/314
/cc @johnbelamaric

Force Ansible handlers

---

.gitattributes

[Windows users](https://github.com/nephio-project/docs/pull/20) have to configure `core.autocrlf` to avoid any change on the repo. The `.gitattributes` file offers the alternative to configure the repository to provide a consistent behavior.

Create repository settings

---

e2e/provision/galaxy-requirements.yml

The [kpt Galaxy role](https://github.com/andrewrothstein/ansible-kpt) has been recently updated. This change has somehow affected the version used by this project. This change updates the version used by the Sandbox installation process.
Fixes: https://github.com/nephio-project/nephio/issues/317
\cc @denysaleksandrov

Bump andrewrothstein.kpt version to 0.0.3

---

.prow.yaml
e2e/provision/Vagrantfile
e2e/provision/init.sh
e2e/provision/install_sandbox.sh
e2e/terraform/main.tf
e2e/terraform/variables.tf

This PR centralizes the`init.sh` script usage. Terraform (e2e CI process) and Vagrant (local) provisioning process will be using the same script. This will provide the same developer experience for the distinct provisioning process.

Use init.sh bash script as main starting point

---

e2e/provision/README.md
e2e/provision/init.sh

The default value of `/home/NEPHIO_HOME`  at line 31 in `init.sh` will never be set because `HOME` is a system variable and always has a value:
```
HOME=${HOME:-/home/$NEPHIO_USER}
```
`init.sh` is amended to pass the `NEPHIO_HOME` variable to the script and change line 31 to
```
HOME=${NEOHIO_HOME:-/home/$NEPHIO_USER}
```
This allows a user to change `HOME` if they like (by setting NEPHIO_HOME) but its likely the default value of `/home/$NEPHIO_USER` will be used in most cases.

Allow nephio home to be configured on install

---

images/gotests/Dockerfile

golang:1.20.4-bullseye -> golang:1.20.5-bullseye
golangci-lint 1.52.2 -> 1.53.3
gosec 2.15.0 -> 2.16.0

Version bumps in gotests adding lichen bin

---

e2e/provision/README.md
e2e/tests/002.sh
e2e/tests/003-network-topo.yaml

This change pretends to make consistent the port values used by `containerlab` and the `RawTopology` resource

Align Network topology values

---

e2e/provision/install_sandbox.sh
e2e/provision/playbooks/roles/bootstrap/README.md
e2e/provision/playbooks/roles/bootstrap/molecule/default/molecule.yml
e2e/provision/playbooks/roles/bootstrap/molecule/default/tests/test_default.py
e2e/provision/playbooks/roles/bootstrap/tasks/main.yml
e2e/provision/playbooks/roles/install/molecule/default/molecule.yml
e2e/provision/playbooks/roles/install/tasks/main.yml
e2e/provision/playbooks/roles/kpt/molecule/default/molecule.yml
e2e/provision/playbooks/roles/kpt/molecule/default/prepare.yml
e2e/provision/playbooks/roles/kpt/molecule/default/tests/test_default.py
e2e/provision/playbooks/roles/kpt/tasks/main.yml
e2e/provision/playbooks/roles/kpt/tasks/wait_deployments.yml

The Nephio management cluster is created with `root` user during the execution of the `bootstrap` Ansible role. As a consequence, many tasks have to be executed with elevated permissions. An initial workaround was to fix it after the Ansible execution. This change removes that workaround and includes those instructions as part of the `bootstrap` process.

Import kubeconfig creation into Ansible Role

---

e2e/provision/Vagrantfile
e2e/provision/init.sh
e2e/provision/install_sandbox.sh

This change allows using the [`vagrant` tool](https://www.vagrantup.com/) to provision an instance in GCE. It needs some [setup](https://github.com/mitchellh/vagrant-google/#google-cloud-platform-setup) previous to its execution:
```bash
GOOGLE_PROJECT_ID=<project_id> GOOGLE_JSON_KEY_LOCATION=<path> NEPHIO_USER=$USER vagrant up --provider google
```
> Note: The `get_status` offers current information about the VM in case that an error happens.

Enable Google vagrant provider

---

e2e/provision/init.sh
e2e/provision/install_sandbox.sh
e2e/provision/playbooks/cluster.yml
e2e/provision/playbooks/roles/bootstrap/README.md
e2e/provision/playbooks/roles/bootstrap/molecule/default/molecule.yml
e2e/provision/playbooks/roles/bootstrap/molecule/default/prepare.yml
e2e/provision/playbooks/roles/bootstrap/tasks/load-gtp5g-module.yml
e2e/provision/playbooks/roles/bootstrap/vars/redhat.yml
e2e/provision/playbooks/roles/bootstrap/vars/ubuntu-22.yml
e2e/provision/playbooks/roles/kpt/molecule/default/prepare.yml

This PR adds support for Fedora34 that has the kernel version of 5.17.6. Was able to execute the steps at https://github.com/nephio-project/test-infra/blob/main/e2e/provision/README.md successfully.
Note:
-  Fedora versions above 34 have kernel version greater than 6.0.0 which does not support building and installing gtp5g kernel modules.
-  PR was tested on a Fedora VM running on baremetal
- Fedora 34 VM on gcp cloud does not allow ssh login and hence was unable to test out in gcp fedora34 VM.

add fedora support

---

prow/config/config.yaml

Since there is no mechanism to link/make dependencies in jobs for now, we are going to build every image in 'nephio' every time something changes in repo, also lowered pod mem request

Enabling building all images in nephio in the same time

---

e2e/tests/008.sh

@@ -35,7 +35,7 @@ function _check_scale {
echo "UPF - Comparing the new $metric after scaling"
-    if [ "$previous" -le "$current" ]; then
+    if [ "$previous" -ge "$current" ]; then
echo "UPF $metric scaling Failed"
exit 1
fi

008.sh corrects the metrics check

---

e2e/tests/007.sh

This change includes a condition that verifies the existence of uesimtun0 NIC as well as restricting the number of pings made during the call simulation

Add a conditional validation for uesimtun0 network interfaces

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/enhancement.md
.github/PULL_REQUEST_TEMPLATE.md

This change provides templates for the creation of Issues and Pull requests. The main goal is to improve the information provided when a change is submitted or an error is detected.

Enable GitHub Issue and PR templates

---

e2e/provision/hacks/vlan-interfaces.sh

In my case, I had 2 resources which matched `clusters` shortcut
- clusters.clusterregistry.k8s.io
- clusters.cluster.x-k8s.io
If specific resource is not specified, `kubectl get clusters` command can return empty list, which is unexpected.

Update vlan-interfaces.sh to indicate specific API

---

e2e/provision/hacks/inter-connect_workers.sh

/kind bug
"cluster" seems to no longer be non-ambiguous. Another question is do we need clusterregistry clusters? Is that needed for CAPI?

Use non-ambigous value for cluster resources

---

e2e/provision/init.sh

/kind bug
**What this PR does / why we need it**
init.sh currently only works if the value passed into nephio-test-infra-branch is a *branch*, not if it is a *tag*. This is a problem for creating instructions that enable building a sandbox from a single command, based on a tag (e.g., v1.0.0).
Partially fixes https://github.com/nephio-project/nephio/issues/328
This will fix it for v1.0.1 and later. For v1.0.0, we need to create a branch to use, and tweak the instructions to use that branch name. Either that, or we need to move the v1.0.0 tag to a commit after this PR merges.
```release-note
NONE
```

Fix init.sh to work with a tag

---

e2e/tests/009.sh

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```

Avoid aborting script if subshell command fails

---

e2e/provision/playbooks/roles/bootstrap/tasks/load-sctp-module.yml

>
/kind bug
> /kind design
> /kind flake
Some Fedora 34 distros don't have support for specific kernel modules packages, this results in failures during the installation of `"kernel-modules-extra-{{ ansible_kernel }}"` package. This change tries to cover all the scenarios and fixes some linting issues
Fixes #
```release-note
```

Fix kernel modules installation

---

e2e/.gitignore
e2e/provision/playbooks/cluster.yml
e2e/provision/playbooks/roles/bootstrap/tasks/create-mgmt.yml

/kind feature
It enables the ansible playbook to set docker registry mirrors for the docker engine in the sandbox VM and also for the management kind cluster deployed by the playbook. The list of registry mirrors is expected to be in the DOCKER_REGISTRY_MIRRORS environment variable in JSON format.
We need this, because in some company intranets DockerHub access has to go through a company-wide docker registry mirror by company policy.
Fixes #
```release-note
Enable setting docker registry mirrors in the sandbox environment.
```

Add docker registry mirror support

---

.prow.yaml

Setting Fedora job as optional will not block merge to e2e
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Setting Fedora job as optional will not block merge to e2e
Fixes #
```release-note
```

Make Fedora job non-blocking

---

e2e/provision/init.sh
e2e/provision/install_sandbox.sh
e2e/provision/playbooks/roles/bootstrap/tasks/prep-gitea.yml

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
This PR is a follow on to https://github.com/nephio-project/test-infra/pull/182 and a)relies on environment variable look up rather than pass them as extra-args to an ansible playbook b)uses the ansible.builtin.command instead of ansible.builtin.shell that allows for ansible-lint checks to pass
Fixes #
```release-note
NONE
```

look up environment variables instead of passing as extra-args

---

.prow.yaml
images/linter/Dockerfile

>
> /kind bug
> /kind design
/kind feature
> /kind flake
There are some linting rules which need to be applied to the `e2e/provision` folder every time that a new change is detected on that folder. This change provides a prow job to achive that.
Fixes #
The `nephio/linter:1` docker image needs to be published before merging this patch.
```release-note
```

Enable tox linter in provision folder

---

e2e/provision/Vagrantfile

>
> /kind bug
> /kind design
/kind feature
> /kind flake
This change provides a way to export Nephio WebUI port to the host machine.
Depends-on: https://github.com/nephio-project/nephio-packages/pull/32
Fixes # https://github.com/nephio-project/nephio/issues/258
```release-note
Expose Nephio WebUI service to the host machine 
```

Expose WebUI port thru Vagrant

---

images/molecule/Dockerfile

>
/kind bug
> /kind design
> /kind flake
Molecule image build is failing on pinned openssh-clients version typo
```
E: Version '1:9.2p1-2' for 'openssh-client' was not found
```
Fixes #
```release-note
```

Fix for molecule image build

---

images/molecule/Dockerfile

>
/kind bug
> /kind design
> /kind flake
Prow seems to mount and execute jobs with `root` user, using a different one causes `Permission denied` [errors](http://prow.nephio.io/view/gs/prow-nephio-sig-release/pr-logs/pull/nephio-project_test-infra/186/bootstrap-integration/1712572612661481472). This change removes the `molecule` user creation
Fixes #
This container image has not been used by prow jobs yet. …

Fix permissions during molecule execution

---

images/e2e/Dockerfile

>
/kind bug
> /kind design
> /kind flake
In the mean time python version in 'world' changed and pinned version causes image build to fail
```
ERROR: unable to select packages:
python3-3.11.6-r0:
breaks: world[python3=3.11.5-r0]
satisfies: python3-3.11.6-r0[python3~3.11]
```
Fixes #
https://prow.nephio.io/view/gs/prow-nephio-sig-release/logs/build-push-image-e2e/1714586107494010880
```release-note
```

Fix python version in e2e image

---

prow/config/config.yaml

>
/kind bug
> /kind design
> /kind flake
Apparently Prow periodic jobs do not clone any repo by default, so it's necessary to specify the repositories to be used. This change fixes the periodic prow definition.
Fixes #
Once this is merged, it's necessary to see the results in the [dashboard](http://prow.nephio.io/?type=periodic)
```release-note
```

Add extra_refs in prow periodic jobs

---

prow/config/config.yaml

Adding path alias in extra_refs and changing execution path in e2e periodics
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Periodic jobs doesn't checkout anything by default, extra_refs will do that so the execution path should be different
Fixes #
```release-note
```

Adding path alias in extra_refs and changing execution path 

---

e2e/provision/playbooks/cluster.yml

/kind cleanup
This passes the HTTP proxy environment variables set in the host environment that runs the ansible playbook to the newly installed Docker daemon and to the tasks of the ansible playbook itself.
It is a step toward fixing https://github.com/nephio-project/nephio/issues/409 , but it will not completely fix the issue.
```release-note
NONE
```

Pass HTTP proxy environment variables to the Docker daemon 

---

e2e/provision/Vagrantfile
e2e/provision/init.sh
e2e/provision/install_sandbox.sh
e2e/provision/playbooks/cluster.yml

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Ansible allows overriding the default value of roles with [different methods](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html#understanding-variable-precedence). This change provides a method to allow the users to pass new values from bash.
Fixes #
```release-note
```

Enable add Ansible extra var list

---

e2e/e2e.sh
e2e/provision/Vagrantfile
e2e/provision/playbooks/roles/install/defaults/main.yml
e2e/tests/oai/002-oai-operators.yaml
e2e/tests/oai/002.sh

>
> /kind bug
> /kind design
/kind feature
> /kind flake
This change provides the resources to deploy OAI controllers. It validates the creation of `packagevariant` and `deployment` resources
Fixes #
It requires using the E2ETYPE env to `oai` value
```release-note
Deploy OAI controllers in regional and edge clusters
```

Enable 002 OAI End-to-End test

---

e2e/tests/free5gc/002.sh
e2e/tests/oai/001.sh
e2e/tests/oai/clab-topo.gotmpl

>
/kind bug
> /kind design
> /kind flake
The OAI containerlab network name doesn't match with the name used by free5gc. This could result in connectivity issues. As improvement, it was included a waiting process for Network instance resources.
Fixes #
```release-note
```

Small improvements on e2e scripts

---

e2e/tests/oai/003.sh
e2e/tests/oai/network-topo.tmpl

>
/kind bug
> /kind design
> /kind flake
In order to establish a PFCP session, it's necessary to validate the connectivity between UPF and SMF components, this requires the proper network setup between the edge and core clusters. This change fixes the topology and includes a method to validate the heartbeat request.
Fixes #
```release-note
```

Fix OAI topology

---

.prow.yaml
e2e/lib/kpt.sh
e2e/lib/porch.sh
e2e/provision/Vagrantfile
e2e/provision/init.sh
e2e/provision/install_sandbox.sh
e2e/terraform/main.tf
e2e/terraform/modules/gcp/main.tf
e2e/terraform/modules/gcp/variables.tf
e2e/tests/free5gc/004.sh
e2e/tests/free5gc/005.sh
e2e/tests/free5gc/006.sh
e2e/tests/free5gc/007.sh
e2e/tests/oai/004-ran-network.sh
e2e/tests/oai/005-ue.sh
prow/config/config.yaml

>
> /kind bug
> /kind design
/kind feature
> /kind flake
The current test-infra End-to-End testing behavior continues executing tests until the end. In some cases, this could extend the testing time and block or misuse the CI resources. This change enables a feature to stop the End-to-End execution if a failure is previously raised.
Fixes #
```release-note
```

Enable `fail fast` CI feature to reduce the End-to-End testing consumption

---

e2e/provision/init.sh
e2e/provision/playbooks/roles/bootstrap/README.md
e2e/provision/playbooks/roles/bootstrap/defaults/main.yml
e2e/provision/playbooks/roles/bootstrap/molecule/ci/molecule.yml
e2e/provision/playbooks/roles/bootstrap/tasks/main.yml
e2e/provision/playbooks/roles/bootstrap/tasks/prechecks.yml

>
> /kind bug
> /kind design
/kind feature
> /kind flake
These changes fix the one-liner bash Sandbox install instruction `curl -fsSL https://raw.githubusercontent.com/nephio-project/test-infra/main/e2e/provision/init.sh | sudo -E bash` which in some cases can be useful to provision Nephio Sandboxes. It also separates the Sandbox Hardware requirements from the requirements to execute End-to-End tests and tries to reduce the provisioning time by skipping the building/loading gtp5g kernel module in OAI test cases.
**Which issue(s) this PR …

Fix one-liner bash Sandbox install

---

prow/config/config.yaml

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Until now, OAI e2e execution is done on demand basis. That restriction limits the capability for catching errors on new changes. This change enables the End-to-End test execution for OAI use case.
Fixes #
```release-note
```

Enable periodic task execution for OAI End-to-End testing

---

e2e/provision/playbooks/roles/install/tasks/main.yml

/kind feature
Stock repos are not visible as `external-blueprints` the tutorial will not properly. 
Fixes # Deploying `free5gc-cp` via the webui in the r2 docs
```release-note
```

Adding a label for stock repos to be visible in external blueprints

---

e2e/provision/playbooks/cluster.yml

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Adds the porchctl binary to the sandbox installation.
The porchctl cmd replaces the kpt alpha cmd set.
Adds the missing porchctl binary
Fixes #
NA
Addition of new porchctl commands
```release-note
Add the porchctl cli tool
```

Add porchctl bin to sandbox install

---

e2e/tests/free5gc/001.sh
e2e/tests/free5gc/003.sh
e2e/tests/free5gc/008.sh
e2e/tests/free5gc/009.sh
e2e/tests/oai/001b-infra-metal-lb.sh

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Update kpt alpha cmds to use porchctl
Using deprecated command
Fixes #
NONE
```release-note
```

Update kpt alpha to use porchctl

---

e2e/provision/init.sh

/kind feature
This PR validates sudo/root permissions for the current user as well as NEPHIO_USER. This ensures the current user and NEPHIO_USER both have passwordless sudo permissions. It also validates that the current user is root (required for `runuser` commands) and that NEPHIO_USER is not root. This was implemented after discussion about needing improvement to user validation. Special notes below note an alternate implementation, if desired.
Fixes #
NONE
There is an alternate implementation that validates the local user is *not* root, and thus changes the `runuser` commands to be `sudo -u` commands. This may cause user facing changes, and thus …

Local and Nephio User Validation

---

.prow.yaml

>
> /kind bug
> /kind design
> /kind flake
/kind feature
This PR adds support or running OAI e2e tests on the Fedora 34 OS
Fixes #
```release-note
NONE
```

add support for OAI e2e tests for fedora34

---

e2e/packer/gcp/main.pkr.hcl

>
/kind bug
> /kind design
> /kind flake
Fixes 
```
* failed to read credentials from file: read /etc/satoken: is a directory
```
https://prow.nephio.io/log?job=pre-bake-daily-ubuntu-jammy&id=1780249906598907904
Fixes #
```release-note
```

Fixing token path

---

prow/config/config.yaml

>
> /kind bug
> /kind design
> 
/kind feature
> /kind flake
This PR follows up on PR https://github.com/nephio-project/test-infra/pull/251 adding OAI e2e testing for Fedora 34, and addresses https://github.com/nephio-project/nephio/issues/590, adding a "periodics" entry to support daily OAI tests on Fedora 34.
Fixes #590
This is added using previous entries as reference, so please inform if there are changes needed or specific ways to test this entry. 
**Does this PR …

Add Fedora 34 OAI Periodic to Config

---

images/gotests/Dockerfile

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
This PR updates the go tests to use go 1.22
Fixes [Issue-510](https://github.com/nephio-project/nephio/issues/510).
```release-note
NONE
```

Update gotests to Go 1.22

---

e2e/e2e.sh
e2e/provision/init.sh
e2e/provision/playbooks/roles/bootstrap/defaults/main.yml
e2e/provision/playbooks/roles/bootstrap/tasks/load-gtp5g-module.yml

>
> /kind bug
> /kind design
/kind feature
> /kind flake
In some scenarios the [free5gc validation](https://github.com/nephio-project/test-infra/blob/main/e2e/provision/playbooks/roles/bootstrap/tasks/main.yml#L16) could not be suficient to prevent the execution of the gtp5g playbook, this requires an additional check to ensure that VM is using the correct kernel version. This change provides an assertion in to the code and upgrades the code version utilized.
Fixes # …

Upgrade gtp5g version and enable verifiers

---

e2e/terraform/modules/gcp/main.tf

>
> /kind bug
> /kind design
/kind feature
> /kind flake
When the PROW job is interrupted by external factors, the VM instance is running on the GCP cloud causing cloud costs to the CI. This change pretends to destroy unused VMs after 2 hours.
Fixes #
```release-note
```

Autodestroy CI VMs after two hours

---

images/generic-autobumper/Dockerfile
images/generic-autobumper/autobumper_config.yaml

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Upgrades prow autobumper to go 1.22 and newer base image
Fixes #
```release-note
```

Autobumper upgrade

---

e2e/lib/k8s.sh
e2e/lib/kpt.sh
e2e/lib/porch.sh
e2e/tests/free5gc/001.sh
e2e/tests/free5gc/003.sh
e2e/tests/free5gc/008.sh
e2e/tests/free5gc/009.sh
e2e/tests/oai/001b-infra-metal-lb.sh

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
This PR adds a log at the end of each wait in the e2e tests so that we can extract the time that each part of the e2e test finished at from the log of the e2e tests. This allows us to get a better picture of what is happening in the e2e runs.
Once this PR is merged we can parse the logs to monitor the times for k8s resources to come up and for porch package approval.
Related to:
https://github.com/nephio-project/nephio/issues/462
**Special notes for …

Add logs for wait end times and porch package approval times to e2e tests

---

e2e/lib/log2timestampcsv.py

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
This PR adds a python script that extracts timestamped logs from the e2e log file, formats them as CSV files, and determines if the time interval between two adjacent log entries is a long delay. The CSV files can then be pulled into a spreadsheet and analysed.
Related to:
https://github.com/nephio-project/nephio/issues/462
None
None

Script for extracting timestamped entries from e2e test logs

---

e2e/provision/init.sh
e2e/provision/playbooks/cluster.yml

>
/kind bug
> /kind design
> /kind flake
`ansible.builtin.yum` seems to be finally deprecated in favor of `ansible.builtin.dnf` module, this decision is impacting the Ansible linting process. It was also reduced the length of the variables and included a disk usage metric.
Fixes #
```release-note
```

Fix Ansible linting issues

---

images/molecule/Dockerfile

Reverts nephio-project/test-infra#270
Seems like it might cause molecule errors in bootstrap-integration tests, reverting for now, it will have to be worked on after the release

Revert "Update Dockerfile - version bump."

---

images/molecule/Dockerfile

Seems like tox version bump  might cause molecule errors in bootstrap-integration tests, reverting for now, it will have to be worked on after the release, this will fix failing image build by bumpping openssh-client version to one present in repositories.

Bumping openssh-client version to unbroke build after the revert of 276

---

e2e/provision/init.sh
e2e/provision/install_sandbox.sh
e2e/provision/playbooks/cluster.yml
e2e/provision/playbooks/roles/bootstrap/tasks/main.yml

>
> /kind bug
> /kind design
kind feature
> /kind flake
This PR allows for deploying nephio management components on pre-existing K8S cluster using the existing scripts. On a machine with K8S installed, one would be able to execute the below command with correct values to install Nephio management components.
`wget -O - https://raw.githubusercontent.com/nephio-project/test-infra/v2.0.0/e2e/provision/init.sh |  sudo NEPHIO_DEBUG=false NEPHIO_BRANCH=v2.0.0 NEPHIO_USER=ubuntu K8S_CONTEXT=kubernetes-admin@kubernetes bash
`
The value for …

adds support in scripts for deploying nephio components on real K8S(non-kind)

---

.prow.yaml

>
/kind bug
> /kind design
> /kind flake
This PR addresses an issue with automated image signing introduced in #266. In #266 we missed tagging the `nephio/releaser` image with `latest` tag. This caused the image signing process to fail because all images tried to pull `nephio/releaser:latest` but couldn't find it.
This PR fixes the issue by ensuring the `nephio/releaser` image is tagged with the `latest` tag along with `${PULL_BASE_REF}`. This will allow all images to successfully pull and use the `nephio/releaser:latest` …

fix: Add latest tag for releaser image

---

prow/config/config.yaml

The path changed in Dockerfiles and the location, so that has to be reflected in Prow's configuration
>
/kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```

Fix porch release images builds

---

prow/config/plugins.yaml

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
invalidcommitmsg plugin checks for 'hash' or 'at' in commit msg which might trigger some actions in GitHub like closing issues. We don't have this problem and it prevents from linking to issue or adding 'fixes...'
Fixes #
```release-note
```

Removing invalidcommitmsg plugin

---

e2e/provision/playbooks/roles/install/defaults/main.yml
e2e/provision/playbooks/roles/install/tasks/main.yml
e2e/provision/playbooks/roles/kpt/tasks/main.yml

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Sets the inventory-id, resource group name and namespace parameters of the `kpt live init` call for the porch kpt package.
Setting these parameters explicitly (as opposed to using the default random values) will help us to use the sandbox for porch development, and it shouldn't make any noticeable difference for normal users of the Nephio sandbox VM.
Fixes #
no issue …

Set explicit inventory parameters while installing porch

---

e2e/provision/playbooks/roles/bootstrap/tasks/main.yml

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Deletes a dockerhub secret when it is present. This was noted on our testing on Fedora, where when a cluster was in a state that the init needed to be run again, the dockerhub secret needed to be deleted to proceed.
Fixes #
```release-note
NONE
```

Delete a Dockerhub secret before attempting to create on during init

---

e2e/provision/playbooks/cluster.yml

>
> /kind bug
> /kind design
/kind feature
> /kind flake
It shows the output of the `porchctl version` command as part of the bootstrap ansible playbook.
It helps troubleshooting end-to-end tests by adding the version of `porchctl` to the logs.
none
```release-note
NONE
```

Show the output of `porchctl version` during bootstrap

---

e2e/provision/playbooks/deploy_kubeadm_k8s.yml

>
/kind bug
> /kind design
> /kind flake
Previously there was a potential condition where the galaxy requirements were not satisfied before running the deploy_kubeadm_k8s.yml script. The install would only happen during init.sh.
Fixes #
```release-note
NONE
```

Adding ansible galaxy install pre_task to deploy_kubeadm_k8s

---

prow/config/config.yaml

>
/kind bug
> /kind design
> /kind flake
Force packer to replace VM image in GCP to always have the same name (timestamp is in VM filesystem)
Fixes #
```release-note
```

Force packer to replace existing image

---

e2e/provision/playbooks/roles/install/defaults/main.yml

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Install the fluxcd gitops agents to the sandbox by default to offer an alternative to configsync.
Fixes #
```release-note
Install fluxcd controllers (Helm, Kustomize, Source, Notification) to sandbox deployment by default.
```

Add fluxcd install by default

---

e2e/provision/playbooks/cluster.yml

/kind cleanup
We changed the name of the  development release of porch from 'main' to 'dev'. This PR deals with the consequence of that.
It is the companion PR of this: https://github.com/nephio-project/porch/pull/175
```NONE
```

Replace porchctl main release with dev release

---

images/gotests/Dockerfile

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Bump go version in testing base image
Fixes #
```release-note
Bump gotests base image go version to v1.23.5
```

Bump go version and tools for gotests base image

---

images/e2e/Dockerfile
images/generic-autobumper/Dockerfile
images/gotests/Dockerfile
images/gotests/checklicense.sh
images/label_sync/Dockerfile
images/linter/Dockerfile
images/molecule/Dockerfile
images/releaser/Dockerfile
tools/release/tag-catalog-packages.sh

add missing license headers to source code files like` *.go, *.sh and Dockerfile and Makefile`
add missing license headers to source code files like` *.go, *.sh and Dockerfile and Makefile`
Several source code files has missing license headers as per `FOSSology report`. This PR adds missing license header to those files.
This is from `SIG Security` team to comply with `FOSSology report`
No

add missing license headers

---

e2e/provision/playbooks/roles/bootstrap/defaults/main.yml
e2e/provision/playbooks/roles/bootstrap/tasks/apply-pkgs-nonkind-k8s.yml
e2e/provision/playbooks/roles/bootstrap/tasks/main.yml

>
> /kind bug
> /kind design
kind feature
> /kind flake
This PR adds support for installing the CAPI metal3 components in order to be able to create baremetal clusters.
Fixes #
Adds support for the CAPI metal3 provider components.
The successful run of tests in this PR depends on the PR at https://github.com/nephio-project/catalog/pull/104 being merged.
```release-note
```

adds support for installing CAPI metal3 components

---

.prow.yaml
e2e/tests/argocd/001.sh
e2e/tests/argocd/002-free5gc-cp.yaml
e2e/tests/argocd/002.sh
prow/config/config.yaml

>
> /kind bug
> /kind design
/kind feature
> /kind flake
This PR adds a ArgoCD Workload Cluster E2E Test
Fixes #
Question: 
- Does having the cluster here named "regional" conflict with the Flux test also using the name "regional"?
This test and prow job situation is modeled after the Flux test, so input as to if something should change would be appreciated. This was tested on my lab VM and passed, but obviously the full prow/daily test run was not tested
**Does this PR …

ArgoCD e2e Test

---

e2e/provision/playbooks/roles/bootstrap/defaults/main.yml
e2e/provision/tox.ini
e2e/tests/free5gc/008.sh

>
> /kind bug
> /kind design
> /kind flake
Bump gtp5g kernel module to fix failing Free5GC UPF deployments
Fixes #
```release-note
NONE
```

Upgrade gtp5g kernel mod to 0.9.15
