nephio-project/test-infra

.prow.yaml
prow/cluster/01-config-generic.yaml
prow/config/config.yaml

Added inrepoconfig and first config verification job for test-infra

Inrepoconfig for test-infra

---

prow/config/config.yaml

job was cloning the same repo twice causing error with validation

test-infra inrepoconfig fix

---

prow/config/config.yaml

Update config.yaml to monitor edge-status-aggregator repo

Update config.yaml to monitor edge-status-aggregator repo

---

prow/config/plugins.yaml

Regarding https://github.com/nephio-project/nephio/issues/99 - enable 'retitle' plugin

enable retitle plugin

---

prow/config/config.yaml

Fixes https://github.com/nephio-project/nephio/issues/132

change merge method to squash on core repos

---

e2e/provision/gce_run.sh

This change improves the idempotency of `gce_run_sh` script, reducing the operations to execute in case the VM has already executed those instructions.

Improve gtp5g kernel module installation

---

prow/config/config.yaml

Docker image build and push jobs for [kpt-backstage-plugins](https://github.com/nephio-project/kpt-backstage-plugins) for every commit and on release

Enable image build for kpt-backstage-plugins

---

prow/config/config.yaml

Images build:
- specializer-operator
- interface-fn
- ipam-fn
- nad-fn
- nfdeploy-fn images:
- amf-deploy-fn
- smf-deploy-fn
- upf-deploy-fn
- vlan-fn

Image building for nephio repository

---

prow/config/config.yaml

Adding watcher-agent and nf-deploy-controller

Adding two more image builds

---

e2e/provision/Vagrantfile
e2e/provision/gce_run.sh
e2e/provision/nephio.yaml
e2e/provision/playbooks/cluster.yml
e2e/provision/playbooks/free5gc.yml
e2e/provision/playbooks/roles/bootstrap/tasks/main.yml
e2e/provision/playbooks/roles/install/tasks/main.yml
e2e/provision/playbooks/roles/kpt/tasks/main.yml
e2e/provision/playbooks/roles/kpt/tasks/wait_deployments.yml
e2e/terraform/main.tf

This change the set of instructions to test the workload provisioning process through Cluster API, these steps will be moved to integration tests later.

Deploy Nephio workload

---

prow/config/plugins.yaml

Fixes https://github.com/nephio-project/sig-release/issues/36

enabling lifecycle plugin

---

e2e/provision/README.md

This adds a regional label to the regional cluster.

Add regional label

---

.prow.yaml
images/label_sync/Dockerfile

Builds for homebrewed images

---

e2e/tests/006.sh

- Correct some editorial errors for TEST-NAME
- Correct name for packagevariant: modify 'smf' to 'upf'

 Correct test-name and packagevariant name

---

.prow.yaml
images/generic-autobumper/Dockerfile

This is image for running generic-autobumper for https://github.com/nephio-project/sig-release/issues/8

Adding generic-autobumper image for prow updater

---

e2e/provision/README.md

This PR improves the documentation by adding a content section and collapsing outputs. It suggests to use absolute paths for placing kpt packages and utilizes Kubernetes context.

Improve documentation format

---

e2e/provision/gce_install_sandbox.sh
e2e/provision/playbooks/roles/kpt/defaults/main.yml
e2e/provision/playbooks/roles/kpt/tasks/main.yml

Solves: https://github.com/nephio-project/nephio/issues/287

Provide default reconcile timeout value

---

e2e/provision/README.md
e2e/tests/003-network-topo.yaml
e2e/tests/003.sh

Adds the configuration of the resource backend for the current static topology.

Add resource backend config

---

e2e/e2e.sh
e2e/launch.sh
e2e/lib/k8s.sh
e2e/lib/testing.sh
e2e/provision/bash_config.sh
e2e/provision/gce_init.sh
e2e/provision/gce_install_sandbox.sh
e2e/provision/hacks/resolve_secrets.sh
e2e/tests/000.sh
e2e/tests/001.sh
e2e/tests/002.sh
e2e/tests/003.sh
e2e/tests/004.sh
e2e/tests/005.sh
e2e/tests/006.sh
e2e/tests/007.sh

The [sh](https://github.com/mvdan/sh) tool provides a consistent format for bash scripts. There is a make target which helps to executed: `make fmt`. This PR is the result of that execution.
\cc @johnbelamaric

Fix bash scripts format

---

prow/config/config.yaml

This change is related to https://github.com/nephio-project/nephio/pull/293

fixed paths for new context

---

e2e/tests/008.sh

Draft 008.sh script for UPF scaling

008.sh UPF Capacity Scaling

---

prow/config/config.yaml

This solves https://github.com/nephio-project/nephio/issues/297

Fixed Dockerfile name for nad-fn

---

e2e/tests/002-topo.gotmpl
e2e/tests/002.sh
e2e/tests/003-network-topo.yaml

counting from 1

---

e2e/tests/003-network-topo.tmpl
e2e/tests/003-secret.yaml
e2e/tests/003.sh

net-config takes the ip from the network container and updates the template so the ip address is known to connect and apply the config to the device

net-config

---

prow/config/config.yaml

adding image builds for configinject-fn

adding configinject-fn

---

e2e/lib/k8s.sh
e2e/lib/testing.sh
e2e/provision/init.sh

This change provides better information when an error happens on the e2e execution.

Improve errors information

---

e2e/lib/k8s.sh
e2e/tests/008.sh

moved scale check to lib and handle mCPU and Integer Cores

008.sh - moved scale check to lib and handle mCPU and Integer Cores

---

e2e/provision/ansible.cfg
e2e/provision/init.sh
e2e/provision/install_sandbox.sh

This change ensures to use a specific Ansible configuration

Enable ansible global configuration

---

.prow.yaml
images/releaser/Dockerfile
images/releaser/release.sh

This will be image to support release process (sbom generation, tagging and uploading images)

Releaser image

---

e2e/e2e.sh
e2e/lib/testing.sh
e2e/tests/009.sh
images/releaser/release.sh

>
> /kind bug
> /kind design
/kind flake
* Enable tests to keep running even if one test script fails
* Add a PASS and FAIL so it shows up in the Prow page
* Add a test summary for all e2e test scripts
* Fix two sources of flakes in 009.sh
* make fmt
Fixes #
```release-note
NONE
```
/hold

Reduce flakes and better test output

---

e2e/provision/playbooks/cluster.yml
e2e/provision/playbooks/roles/bootstrap/README.md
e2e/provision/playbooks/roles/bootstrap/defaults/main.yml
e2e/provision/playbooks/roles/install/README.md
e2e/provision/playbooks/roles/install/defaults/main.yml
e2e/tests/004-free5gc-operator.yaml
e2e/tests/005-edge-free5gc-upf.yaml
e2e/tests/006-regional-free5gc-amf.yaml
e2e/tests/006-regional-free5gc-smf.yaml
e2e/tests/007-edge01-ueransim.yaml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```

Bump version to 1.0.1

---

e2e/lib/k8s.sh

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Allows for running sandbox on fedora34 in addition to ubuntu
Fixes #
```release-note
```

uses mktemp function supported both on ubuntu and fedora

---

e2e/provision/playbooks/roles/bootstrap/README.md
e2e/provision/playbooks/roles/bootstrap/molecule/default/tests/test_default.py
e2e/provision/playbooks/roles/bootstrap/tasks/load-sctp-module.yml
e2e/provision/playbooks/roles/bootstrap/tasks/main.yml

>
> /kind bug
> /kind design
> /kind flake
This PR adds code that checks to ensure the sctp kernel module (needed by AMF) is installed and loaded on the host OS.
Fixes #
```release-note
```

install and loads sctp kernel modules needed by AMF

---

e2e/provision/playbooks/library/kpt.py
e2e/provision/playbooks/roles/upgrade/README.md
e2e/provision/playbooks/roles/upgrade/defaults/main.yml
e2e/provision/playbooks/roles/upgrade/molecule/default/converge.yml
e2e/provision/playbooks/roles/upgrade/molecule/default/molecule.yml
e2e/provision/playbooks/roles/upgrade/molecule/default/prepare.yml
e2e/provision/playbooks/roles/upgrade/molecule/default/tests/test_default.py
e2e/provision/playbooks/roles/upgrade/tasks/main.yml
e2e/provision/playbooks/roles/upgrade/tasks/update.yml
e2e/provision/playbooks/roles/upgrade/tasks/wait_deployments.yml
e2e/provision/tox.ini

>
> /kind bug
> /kind design
/kind feature
> /kind flake
This change provides the Ansible role to upgrade the Nephio services. This approach runs `kpt` update commands in parallel and waits for the readiness of the deployments.
Fixes #
It contains molecule test to facilitate the testing (`tox -e upgrade`)
```release-note
Upgrade Ansible Role addition
```

Upgrade Ansible role creation

---

e2e/provision/test-requirements.in
e2e/provision/test-requirements.txt

>
/kind bug
> /kind design
> /kind flake
Molecule plugins binary has been released, so using the repository is not needed anymore
Fixes #
Use a fresh new `tox` environment to validate the installation of dependencies. 
```release-note
```

Fix molecule test python dependencies

---

e2e/e2e.sh
e2e/lib/_utils.sh
e2e/lib/k8s.sh
e2e/lib/testing.sh
e2e/provision/hacks/inter-connect_workers.sh
e2e/provision/hacks/vlan-interfaces.sh
e2e/tests/001.sh
e2e/tests/002.sh
e2e/tests/003.sh
e2e/tests/004.sh
e2e/tests/005.sh
e2e/tests/006.sh
e2e/tests/007.sh
e2e/tests/008.sh
e2e/tests/009.sh

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Most of the testing bash function use similar values, using default arguments can facilitate the readability and reduce errors. This change refactor the testing bash functions and reduces some complexity on them as well as fixes some linting issues.
Fixes #
```release-note
```

Refactor End-to-End bash testing scripts

---

e2e/lib/k8s.sh
e2e/tests/007.sh
e2e/tests/008.sh
e2e/tests/009.sh

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
This change extracts the instructions to get the newest pod name and refactor some other instructions to facilitate the reading of the testing code.
Fixes #
```release-note
```

Refactor 007, 008 and 009 test scripts

---

e2e/provision/playbooks/roles/bootstrap/tasks/wait-deployments.yml
e2e/provision/playbooks/roles/install/tasks/wait_deployments.yml
e2e/provision/playbooks/roles/kpt/tasks/main.yml

/kind feature
Makes some ansible task names more descriptive to make it easier to follow the progress of the install process.
This is especially useful for troubleshooting.
Fixes #
```release-note
NONE
```

Make ansible task names more descriptive 

---

prow/config/plugins.yaml

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
By default repo owners' PR is auto approved, this disables that behaviour.
Fixes #
```release-note
```

Require self approval on test-infra

---

.prow.yaml

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
```

Fixing linter version

---

prow/config/config.yaml

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Fixes https://github.com/nephio-project/nephio/issues/387
#387
Fixes #
```release-note
```

Adding gen-configmap-fn build

---

.prow.yaml

Adding linter image build
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Adding linter image build
Fixes #
```release-note
```

Adding linter image build

---

.gitignore
.prow.yaml
e2e/provision/playbooks/roles/bootstrap/molecule/ci/molecule.yml
e2e/provision/playbooks/roles/bootstrap/molecule/default/molecule.yml
e2e/provision/playbooks/roles/install/molecule/ci/molecule.yml
e2e/provision/playbooks/roles/install/molecule/default/molecule.yml
e2e/provision/playbooks/roles/kpt/molecule/ci/molecule.yml
e2e/provision/playbooks/roles/kpt/molecule/default/molecule.yml
e2e/provision/test-requirements.in
e2e/provision/test-requirements.txt
e2e/provision/tox.ini
images/molecule/Dockerfile

>
> /kind bug
> /kind design
/kind feature
> /kind flake
The Ansible roles provided by this project have Integration tests. Those tests were created with [Molecule Ansible framework](https://ansible.readthedocs.io/projects/molecule/) and they are run manually. This change integrates the execution of these tests into the PROW system.
Fixes https://github.com/nephio-project/nephio/issues/381
```release-note
Enable Ansible …
```

Enable Molecule tests in PROW

---

images/molecule/Dockerfile

>
/kind bug
> /kind design
> /kind flake
Prow uses root user during the execution of jobs and molecule GCE requires the USER env var to [perform several tasks](https://github.com/ansible-community/molecule-plugins/blob/v23.5.0/src/molecule_plugins/gce/playbooks/tasks/create_linux_instance.yml#L4). This change fixes the value of the USER environment variable.
Fixes #
```release-note
```

Use root as value for USER env var into molecule Docker image

---

.prow.yaml

>
> /kind bug
/kind cleanup
> /kind design
/kind feature
> /kind flake
This change improves the molecule test execution, utilizing a customized docker image to perform Ansible Role integration tests.
Fixes #
```release-note
```

Use nephio molecule docker image in prow

---

e2e/provision/playbooks/roles/bootstrap/defaults/main.yml
e2e/tests/007.sh
e2e/tests/009.sh

>
> /kind bug
> /kind design
/kind feature
> /kind flake
This release version include some bug fixes and improvements
Fixes #
```release-note
```

Upgrade gtp5G kernel module

---

.prow.yaml
images/e2e/Dockerfile
images/generic-autobumper/Dockerfile
images/label_sync/Dockerfile

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
[Hadolint ](https://github.com/hadolint/hadolint) is a linter tool that enforces to use best practices in Dockerfiles. This enforcement prevents future issues and increases the quality of the source code. This change fixes the current Dockerfiles and enables the Prow job for future changes.
Fixes #
```release-note
```

Enable Dockerfile linter tool

---

prow/config/config.yaml

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Adding image builds for OAI
Fixes #
```release-note
```

Adding OAI images build

---

.prow.yaml
prow/config/config.yaml

>
/kind bug
> /kind design
> /kind flake
Periodic tasks [were moved to in repo config](https://github.com/nephio-project/test-infra/pull/204) to enabled their execution. This change highlighted the importance to use absolute paths. This change provides a fix on the paths as well as the usage of e2e latest tag Docker image
Fixes #
The fix will be shown on the [prow dashboard](http://prow.nephio.io/?type=periodic)
**Does this PR introduce a user-facing …

Fix periodic prow periodic tasks

---

prow/config/config.yaml

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Enabling inrepoconfig for OAI
Fixes #
```release-note
```

Enabling inrepoconfig for OAI

---

prow/config/config.yaml
prow/config/plugins.yaml

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Adds support for Prow jobs being executed on Nephio Experimental Org
Fixes #
https://github.com/nephio-project/nephio/issues/379
```release-note
```

Nephio Experimental configuration

---

prow/config/config.yaml
prow/config/plugins.yaml

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Fixes #
https://github.com/nephio-project/nephio/issues/379
```release-note
```

Enabling Prow for whole Nephio Experimental

---

prow/config/config.yaml

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Recent changes in nephio moved nfdeploy-fn subcomponents to one, aligning docker image build here.
Fixes #
```release-note
```

Aligning nfdeploy-fn builds to code changes

---

.prow.yaml

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Some test images don't have git installed thus rev-parse fails to show top level of directory.
Fixes #
Failing tests in #212 
```release-note
```

Fixing path for images that do not have git installed

---

e2e/e2e.sh
e2e/lib/kpt.sh
e2e/provision/Vagrantfile
e2e/provision/init.sh
e2e/provision/install_sandbox.sh
e2e/provision/playbooks/roles/bootstrap/tasks/prechecks.yml

>
/kind bug
> /kind design
> /kind flake
This PR fixes the usage of the ANSIBLE_CMD_EXTRA_VAR_LIST, from an iteration of a comma separated values to a single string. It includes additional improvements to control the e2e behavior. 
Fixes #
Use a ANSIBLE_CMD_EXTRA_VAR_LIST string value
```release-note
```

Fix ANSIBLE_CMD_EXTRA_VAR_LIST environment variable

---

e2e/tests/oai/001.sh
e2e/tests/oai/002-oai-operators.yaml
e2e/tests/oai/002.sh
e2e/tests/oai/003-upf.yaml
e2e/tests/oai/003.sh
e2e/tests/oai/clab-topo.gotmpl
e2e/tests/oai/network-topo.tmpl

>
> /kind bug
> /kind design
/kind feature
> /kind flake
This change includes the instructions required to deploy OAI Core NFs and some fixes on the Topology which were affecting the allocation of resources.
Fixes #
```release-note
OAI Core NFs End-to-End testing deployment
```

Initial End-to-End script for OAI Core NF deployment

---

prow/config/config.yaml

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Enabling porch presubmit tests according to https://github.com/nephio-project/porch/pull/4
Fixes #
```release-note
```

Enabling porch repo presubmit CI jobs

---

images/gotests/Dockerfile
images/gotests/coverage.sh

>
> /kind bug
> /kind design
/kind feature
> /kind flake
This add gocov and gocov-html for pretty reports as well as coverage delta reporting tool , both for https://github.com/nephio-project/nephio/issues/374
Fixes #
```release-note
```

Adding go coverage reporting

---

prow/config/config.yaml

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Our own builds for porch release images
Fixes #
```release-note
```

Adding porch release images builds

---

e2e/provision/README.md

>
/kind bug
> /kind design
> /kind flake
The doc project has changed its structure, which affects the links on the documentation. This updates the references.
Fixes #
```release-note
```

Update documentation link references

---

e2e/defaults.env
e2e/provision/playbooks/roles/bootstrap/defaults/main.yml
e2e/provision/playbooks/roles/install/defaults/main.yml
e2e/tests/free5gc/001.sh
e2e/tests/free5gc/002-edge-clusters.yaml
e2e/tests/free5gc/002-network.yaml
e2e/tests/free5gc/003.sh
e2e/tests/free5gc/004-free5gc-operator.yaml
e2e/tests/free5gc/005-edge-free5gc-upf.yaml
e2e/tests/free5gc/006-regional-free5gc-amf.yaml
e2e/tests/free5gc/006-regional-free5gc-smf.yaml
e2e/tests/oai/001-infra.yaml
e2e/tests/oai/001-network.yaml
e2e/tests/oai/001b-infra-metal-lb.sh
e2e/tests/oai/002-operators.yaml
e2e/tests/oai/004-ran-network.yaml
e2e/tests/oai/005-ue.yaml

>
> /kind bug
> /kind design
/kind feature
> /kind flake
This change uses the latest catalog revision number for R2
Fixes #
```release-note
```

Update references to v2.0.0 revision

---

tools/release/config.json
tools/release/kraken.py
tools/release/requirements.txt
tools/release/util.py

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Adding release process automation script
Fixes #
```release-note
```

Adding release automation script

---

prow/config/config.yaml

>
/kind bug
> /kind design
> /kind flake
Per commit image builds has to have 'latest' tag as well
Fixes #
```release-note
```

Fix for latest tag in commit image builds for OAI

---

.prow.yaml
e2e/README.md
e2e/provision/init.sh
e2e/provision/install_sandbox.sh
e2e/terraform/modules/gcp/main.tf
prow/config/config.yaml

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Removal/cleanup of old ONES-2022 config and test
Fixes #
NONE
```release-note
```

Remove ones-22 config

---

e2e/lib/_assertions.sh
e2e/lib/k8s.sh
e2e/lib/kpt.sh
e2e/lib/porch.sh
e2e/provision/init.sh
e2e/provision/install_sandbox.sh
e2e/tests/free5gc/001.sh
e2e/tests/free5gc/003.sh
e2e/tests/free5gc/004.sh
e2e/tests/free5gc/005.sh
e2e/tests/free5gc/006.sh
e2e/tests/oai/001a-infra.sh
e2e/tests/oai/001b-infra-metal-lb.sh
e2e/tests/oai/003-core-network.sh
e2e/tests/oai/004-ran-network.sh
e2e/tests/oai/005-ue.sh
images/gotests/coverage.sh
tools/release/tag-catalog-packages.sh

>
> /kind bug
> /kind design
/kind feature
> /kind flake
The current logging instructions generate a lot of entries that sometimes are unnecessary. These changes pretend to reduce them to improve the troubleshooting experience.
Fixes #
```release-note
```

Improve logging process

---

tools/dependabot/generate_dependabot.py

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Dependabot has static configuration that doesn't allow to use globing/regexp etc. so with monorepos it has to be regenerated to reflect codebase changes.
Fixes #
```release-note
```

Dependabot config generator

---

images/gotests/Dockerfile

>
> /kind bug
> /kind design
> /kind flake
golangci-lint update to work with go 1.22 updated other components as well
This resolves failing tests in https://github.com/nephio-project/nephio/pull/597 and https://github.com/nephio-project/nephio/pull/722
Fixes #
```release-note
```

Updating gotests binaries

---

OWNERS

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
```

Adding new reviewers

---

OWNERS

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
```

Add efiacor to OWNERS file

---

.prow.yaml
images/releaser/Dockerfile
images/releaser/release.sh
prow/config/config.yaml

>
> /kind bug
> /kind design
/kind feature
> /kind flake
This PR proposes automating released nephio image signing using cosign. Currently, signing is done manually after the release. This PR aims to integrate signing into the release pipeline.
Fixes https://github.com/nephio-project/nephio/issues/553
```release-note
NONE
```

feat: Automate released image signing

---

OWNERS

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```

Add Liam to approvers list

---

e2e/provision/galaxy-requirements.yml
e2e/provision/requirements.txt
e2e/provision/test-requirements.txt

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Regular task to maintain latest stable versions in their dependencies 
Fixes #
```release-note
```

Upgrade dependencies

---

e2e/provision/install_sandbox.sh

>
kind bug
> /kind design
> /kind flake
When using set -o nounset in Bash scripts variables have to have value, here the default will be all to execute all tags if not overriden 
Fixes #
```release-note
```

Fixing sandbox unbound variable error

---

e2e/defaults.env
e2e/provision/galaxy-requirements.yml
e2e/provision/playbooks/cluster.yml
e2e/provision/playbooks/roles/bootstrap/defaults/main.yml
e2e/provision/playbooks/roles/install/defaults/main.yml
e2e/terraform/modules/gcp/main.tf
e2e/terraform/modules/gcp/variables.tf
e2e/tests/free5gc/002-edge-clusters.yaml
e2e/tests/free5gc/002-network.yaml
e2e/tests/free5gc/004-free5gc-operator.yaml
e2e/tests/free5gc/004.sh
e2e/tests/free5gc/005-edge-free5gc-upf.yaml
e2e/tests/free5gc/005.sh
e2e/tests/free5gc/006-regional-free5gc-amf.yaml
e2e/tests/free5gc/006-regional-free5gc-smf.yaml
e2e/tests/free5gc/006.sh
e2e/tests/free5gc/007-edge01-ueransim.yaml
e2e/tests/free5gc/007.sh
e2e/tests/oai/001-infra.yaml
e2e/tests/oai/001-network.yaml
e2e/tests/oai/001b-infra-metal-lb.sh
e2e/tests/oai/002-database.yaml
e2e/tests/oai/002-operators.yaml
e2e/tests/oai/003-core-network.sh
e2e/tests/oai/003-core-network.yaml
e2e/tests/oai/004-ran-network.sh
e2e/tests/oai/004-ran-network.yaml
e2e/tests/oai/005-ue.sh
e2e/tests/oai/005-ue.yaml

>
> /kind bug
> /kind design
/kind feature
> /kind flake
switching e2e tests from main to v3.0.0
Fixes #
```release-note
```

Switching e2e tests to v3.0.0

---

images/releaser/release.sh

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
In order for automated cosign signing to work releaser image has to have access to image registry authentication config, logic to wait for image build and upload was added.
Fixes #
```release-note
```

Automated signing fixes and improvements

---

prow/config/config.yaml

>
/kind bug
> /kind design
> /kind flake
It add image repository credentials access needed to push the signature
Fixes #
```release-note
```

Fixing image autosign - prow part

---

e2e/defaults.env
e2e/provision/playbooks/cluster.yml
e2e/provision/playbooks/roles/bootstrap/defaults/main.yml
e2e/provision/playbooks/roles/install/defaults/main.yml
e2e/tests/free5gc/002-edge-clusters.yaml
e2e/tests/free5gc/002-network.yaml
e2e/tests/free5gc/004-free5gc-operator.yaml
e2e/tests/free5gc/005-edge-free5gc-upf.yaml
e2e/tests/free5gc/006-regional-free5gc-amf.yaml
e2e/tests/free5gc/006-regional-free5gc-smf.yaml
e2e/tests/free5gc/007-edge01-ueransim.yaml
e2e/tests/oai/001-infra.yaml
e2e/tests/oai/001-network.yaml
e2e/tests/oai/002-database.yaml
e2e/tests/oai/002-operators.yaml
e2e/tests/oai/003-core-network.yaml
e2e/tests/oai/004-ran-network.yaml
e2e/tests/oai/005-ue.yaml

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
After R3 has it's own branch it's time to switch main to work on main again
Fixes #
```release-note
```

Switching back to main

---

images/gotests/Dockerfile

>
> /kind bug
> /kind design
> /kind flake
Lichen license tests are failing recently for example on yaml library with false positive forbidden license detection. This upgrade solves this problem with using lichen fork with newer detection engine.
Fixes #
```release-note
```

Upgrading lichen to version with better license detection

---

images/releaser/Dockerfile

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Image build failing on curl version fix
Fixes #
```release-note
```

Bumping curl version

---

tools/dependabot/generate_dependabot.py

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Adding ok-to-test label for Prow for Dependabot generated pull-requests
Fixes #
```release-note
```

Adding ok-to-test label for Prow

---

e2e/tests/free5gc/006-regional-free5gc-amf.yaml
e2e/tests/free5gc/006-regional-free5gc-smf.yaml
e2e/tests/free5gc/009.sh
e2e/tests/oai/004a-ran-network.sh
e2e/tests/oai/004a-ran-network.yaml
e2e/tests/oai/004b-ran-network.sh
e2e/tests/oai/004b-ran-network.yaml

>
> /kind bug
> /kind design
> /kind flake
Add new always approval policies to PVs that need them
Fixes #
```release-note
NONE
```

Add always approval to selected PVs

---

e2e/lib/testing.sh

>
> /kind bug
/kind design
> /kind flake
This will allow tracing progress of e2e test while logged in the testing VM without relaying on Prow's logs
Fixes #
```release-note
```

Script output logging for e2e tests

---

e2e/provision/playbooks/roles/kubeadm/tasks/kubeadm-RedHat.yml

>
> /kind bug
> /kind design
> /kind flake
Disable gpg checks on yum install for kubeadm fedora install
Fixes #
```release-note
NONE
```

Disable gpg checks on yum kubeadm install

---

e2e/provision/playbooks/roles/install/molecule/default/tests/test_default.py

>
> /kind bug
> /kind design
> /kind flake
Remove porch functions from integration testing
Fixes #
```release-note
NONE
```

Remove porch functions from integration

---

.prow.yaml
prow/config/config.yaml

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Refine when the kubeadm CI jobs are run. Only run when chane is made to the kubeadm dir and once daily by default"
Fixes #
```release-note
NONE
```

Refine kubeadm CI frequency

---

.prow.yaml
e2e/lib/capi.sh
e2e/tests/flux/001.sh
e2e/tests/flux/002-free5gc-cp.yaml
e2e/tests/flux/002.sh
prow/config/config.yaml

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Adds a new test suite to cover - https://github.com/nephio-project/nephio/issues/843
https://github.com/nephio-project/nephio/issues/843
Fixes 843
```release-note
Add new e2e test suite to cover deployment of a workload using fluxcd ksutomize controller.
```

Add fluxcd workload suite

---

prow/config/config.yaml

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Builds release image for: https://github.com/nephio-project/nephio/pull/844
Fixes #
```release-note
```

O2 IMS Operator release image build

---

prow/config/config.yaml

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Release job for nephio focom operator
Fixes #
```release-note
New image job for Nephio Focom Operator
```

Add release job for focom oper image

---

prow/config/config.yaml

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixing image build paths for new operators
Fixes #
```release-note
```

Fixing image build paths for new operators

---

prow/config/config.yaml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```

Quick fix operators

---

prow/config/config.yaml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```

Another operator fix

---

e2e/defaults.env
e2e/provision/playbooks/cluster.yml
e2e/provision/playbooks/roles/bootstrap/defaults/main.yml
e2e/provision/playbooks/roles/install/defaults/main.yml
e2e/tests/flux/002-free5gc-cp.yaml
e2e/tests/free5gc/002-edge-clusters.yaml
e2e/tests/free5gc/002-network.yaml
e2e/tests/free5gc/004-free5gc-operator.yaml
e2e/tests/free5gc/005-edge-free5gc-upf.yaml
e2e/tests/free5gc/006-regional-free5gc-amf.yaml
e2e/tests/free5gc/006-regional-free5gc-smf.yaml
e2e/tests/free5gc/007-edge01-ueransim.yaml
e2e/tests/o2ims/001-sample-provisioning-request.yaml
e2e/tests/oai/001-infra.yaml
e2e/tests/oai/001-network.yaml
e2e/tests/oai/002-database.yaml
e2e/tests/oai/002-operators.yaml
e2e/tests/oai/003-core-network.yaml
e2e/tests/oai/004a-ran-network.yaml
e2e/tests/oai/004b-ran-network.yaml
e2e/tests/oai/005-ue.yaml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```

Switching test-infra to v4.0.0

---

images/gotests/Dockerfile

>
> /kind bug
> /kind design
> /kind flake
Bump versions for gotest image
Fixes #
```release-note
NONE
```

Bump gotest image versions

---

e2e/.gitignore
e2e/provision/tox.ini

>
> /kind bug
> /kind design
> /kind flake
Fix provision-linter job
Fixes #
```release-note
NONE
```

Fix tox provision-linter

---

e2e/provision/playbooks/cluster.yml
e2e/tests/ocloud/001-focom-provisioning-request.yaml

>
> /kind bug
> /kind design
> /kind flake
Improve stability where mgmt Repo take time to be Ready
Fixes #
```release-note
NONE
```

Add wait_timeout for mgmt-* Repos to be ready

---

e2e/provision/playbooks/roles/install/defaults/main.yml

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Adds the [argo-cd-full](https://github.com/nephio-project/catalog/pull/122) catalog package to the sandbox install, for use with the [ArgoCD Workload Cluster](https://github.com/nephio-project/catalog/pull/118) using our [CMP](https://github.com/nephio-project/nephio/pull/942)
Fixes #
```release-note
NONE
```

Add argocd install to sandbox

---

prow/config/config.yaml

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Update weekly jobs to run at 2am Sun to avoid overuse of GCP resources
Fixes #
```release-note
NONE
```

Update weekly jobs to run at 2am

---

e2e/tests/argocd/001.sh
e2e/tests/flux/001.sh
e2e/tests/free5gc/001.sh
e2e/tests/free5gc/003.sh
e2e/tests/oai/001b-infra-metal-lb.sh
e2e/tests/ocloud/001.sh

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Remove git branch log assertions from use case tests 
Fixes #
```release-note
NONE
```

Remove git branch log assertions
